enum AudioKey {
  MOCK_SONG = 'MOCK_SONG',
  MAIN_SONG = 'MAIN_SONG',
  BERSERKER_SONG = 'BERSERKER_SONG',
  FOCUSED_SONG = 'FOCUSED_SONG',
  ANGEL_SONG = 'ANGEL_SONG',
  MEDITATION_SONG = 'MEDITATION_SONG',
  DARK_SONG = 'DARK_SONG',
}

export default AudioKey;
