enum Event {
  ACTIVATE_TAPE_SELECTION = 'ACTIVATE_TAPE_SELECTION',
  DEACTIVATE_TAPE_SELECTION = 'DEACTIVATE_TAPE_SELECTION',
  TAPE_COLLECTED = 'TAPE_COLLECTED',
  RUN_TAPE = 'RUN_TAPE',
}

export default Event;
